### ISSUE TITLE
I can see only one geometry per time in the external rendering

### ISSUE THREAD

**Issue by riccardobl** [xbuf/jme3_xbuf#1]
Video below:
[![Video](http://img.youtube.com/vi/Ed70huddPt0/0.jpg)](https://www.youtube.com/watch?v=Ed70huddPt0)

**Comment by davidB** [comment]
I can't reproduce. Can you send me the .blend ?

![screenshot](http://i.imgur.com/kOwSadC.png)

I notice you don't have the default bg color for viewer. How did you change it ?

Do you have the same issue when you switch between ortho/perspective mode (NUM 5) ?

**Comment by riccardobl** [comment]
Oh, no i think i have the default(gray?) one, just the youtube preview is overbright idk why (if you click on it, you can see the video on yt that should have the default bg)...
This is not the same scene, because i deleted the old one, but the problem is the same https://drive.google.com/file/d/0BwOEIhbHMKaFUjRfdTVuMGhFbUU/view?usp=sharing
If i switch to ortho mode nothing change.

**Comment by riccardobl** [comment]
Well, i don't know if it has been fixed or something, but this issue doesn't exist any more.
