### ISSUE TITLE
The texture panel in blender is blank

### ISSUE THREAD

**Issue by riccardobl** [xbuf/jme3_xbuf#2]
Video below, from 0:15
[![Video](http://img.youtube.com/vi/Ed70huddPt0/0.jpg)](https://youtu.be/Ed70huddPt0?t=15s)

**Comment by davidB** [comment]
should be fix in [define "xbuf render" as compatible with every panel compatible…](https://github.com/xbuf/blender_io_xbuf/commit/6235a3e8a6b0327a9b9d7442fba38df5780a9c5a)

the fix in https://github.com/xbuf/blender_io_xbuf
