### ISSUE TITLE
Seriously why xtend?

### ISSUE THREAD

**Issue by riccardobl** [xbuf/jme3_xbuf#3]
This is not really an issue, but more a feedback.
Being this a plugin for a java engine, i can't understand why it is written in xtend. 
I was thinking about using this in one of my projects, but i need something easy to customize and this abomination known with the name of xtend makes this library the exact opposite for me.

I wish to be clear, i'm not asking you to rewrite this in java, i'm just pointing at the fact that having this written in a different language than the engine is imo a drawback.

**Comment by davidB** [comment]
I'm tired of the Java boiler plate. I daily work with more modern language with type inference, sugar syntax for constructor, no stupid getter/setter,...
I daily work with Scala, but Scala force to use the big jar scala-library (10+ MB). And Scala has some binary incompatibility between minor version.
I previously used "project lombock" + java 8 for my jme lib. But that lock my lib for desktop only and lombok require special compiler installation in IDE that generate trouble.
Then I gave a try to Xtend that is a transpiler that generate pure Java (7 or 8) and that provide more syntax sugar than lombock.

**Comment by davidB** [comment]
One of my last commit require java 8 (closure). So If you want to contribute to loader or an other part if source is in java. May be, I could spend time to convert back to java 8 some sub-project.

Tell me.

**Comment by riccardobl** [comment]
Well, i think this project is interesting but as i said the fact it's written in xtend prevents me from using it and thus also from contributing to it.

**Comment by riccardobl** [comment]
I'm closing my issue.
